site_name: Wretched Tower Documentation
site_url: https://andrlik.github.io/wretched-tower/
site_author: Daniel Andrlik
copyright: Copyright &copy; 2025 Daniel Andrlik
watch: [mkdocs.yml, README.md, CHANGELOG.md, CODE_OF_CONDUCT.md, SECURITY.md, src/wretched_tower]
nav:
  - Home: index.md
  - Reference: reference/
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Security: security.md
  - License: license.md
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: indigo
    accent: deep-purple
repo_url: https://github.com/andrlik/wretched-tower
plugins:
  - search
  - autorefs
  - include-markdown
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_files.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            annotations_path: brief
            docstring_options:
              ignore_init_summary: true
  - mike:
      canonical_version: latest
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - footnotes
    - admonition

extra:
  version:
    provider: mike
